Updated data dump script
Stanford-Online/dump-dbs pull request #3
Opened 2017-05-04 20:23 UTC by axelsly

- Perform deletion in python script
- Perform deletion only after a successful dump
  - dump first
  - if fail: exit,exception,record,notify?
  - delete second
- On script failure send email
- Remove any lingering .sql files
  - However, once the problem gets fixed this should be fine if we delete
    lingering files manually.

2017-05-08 22:50 UTC, axelsly commented
@stvstnfrd @dcadams

2017-07-06 18:07 UTC, caseylitton commented
Do we still use the config_example.yml or is it's name deceiving?  

I see they have different entries but what is the difference between config_example and devstack_config?

2017-07-06 18:32 UTC, stvstnfrd commented
@caseylitton re: `config_example.yml`

Yeah, I'm not sure why he created a new file;
I asked him to update the existing one.

Those changes should be made there.

2017-07-06 20:11 UTC, stvstnfrd requested changes

2017-07-06 20:11 UTC, stvstnfrd commented on .gitignore
> +venv/
Virtualenv's shouldn't need ignored;
they should be created outside of the project directory.

Among other issues, it makes grepping a pain due to false positives.

2017-07-06 20:11 UTC, stvstnfrd commented on devstack_config.yml
> +# Configuration file for the dump_dbs.py utility.
Per discussion elsewhere on the thread, these changes should be made to the existing configuration file.

2017-07-06 20:11 UTC, stvstnfrd commented on dump.sh
> +. /home/vagrant/dump-dbs/venv/bin/activate
This may be a debugging relic that we can remove.
At the least, it shouldn't be hard-coding the user directory.

2017-07-06 20:11 UTC, stvstnfrd commented on dump_dbs.py
> +    with open(target_name, "w") as outfile:
I don't think this is quite right;
the nature of this command appears to be changing slightly.

This is the difference between:

```sh
mongodump -o outfile
```

and

```sh
mongodump > outfile
```

From the manual:
> To output the database dump to standard output, specify a - rather than a path.

This didn't need changed.

2017-07-06 20:11 UTC, stvstnfrd commented on dump_dbs.py
> +    delete_old(failed_db)
This still doesn't check if the dump actually succeeded.

2018-10-18 04:48 UTC, closed without merging